name: ${project.name}
main: ${bukkitMain}
load: STARTUP
version: ${project.version}
description: ${project.description}
website: ${project.url}
authors: [kmecpp]
commands:
  osmium:
    description: Osmium base command