name: ${project_name}
main: ${bukkit_main}
load: STARTUP
version: ${project_version}
description: ${project_description}
website: ${project_url}
authors: [kmecpp]
commands:
  osmium:
    description: Osmium base command