name: Osmium
main: com.kmecpp.osmium.platform.bukkit.OsmiumBukkitMain
version: 1.0
description: API for Bukkit and Sponge
website: https://github.com/kmecpp/Osmium
authors: [kmecpp]
commands:
  osmium:
    description: Osmium base command